"""MIMIC-IV clinical-action routing extraction (RUNNABLE, DATA-FREE).

WHAT THIS DOES
--------------
Reads a *user-supplied* MIMIC-IV v2.x copy, maps each clinical action to an
ORASR risk score via a transparent, documented mapping, routes every action
through the committed ``ORASRRouter``, and emits the same routing-distribution
table the manuscript reports (Fast / Normal / Safe shares over the action
corpus).

WHAT THIS DELIBERATELY DOES *NOT* DO
------------------------------------
* It ships **no** MIMIC-IV data. MIMIC-IV is credentialed data on PhysioNet and
  may not be redistributed (https://physionet.org/content/mimiciv/).
* It does **not** hardcode the manuscript's 8,412-action count or the
  58.1 / 31.5 / 10.4% distribution. Those numbers MUST be regenerated by the
  user on their own credentialed copy. If you run this on the real data you will
  get the empirical distribution for *your* extracted action set; small
  differences from the manuscript are expected if your cohort filter differs.
* If MIMIC-IV is not present, the script exits with a clear message and does
  NOT fabricate any number.

ACCESS REQUIREMENT
------------------
Requires credentialed PhysioNet access to MIMIC-IV. Provide the dataset root
either via ``--mimic-path`` or the ``MIMIC_IV_PATH`` environment variable. The
root must contain the standard ``hosp/`` module (this script uses
``hosp/prescriptions.csv.gz`` and ``hosp/poe.csv.gz`` as the clinical-action
source -- adjust ``ACTION_SOURCES`` if your extract differs).

RISK MAPPING (transparent & auditable)
--------------------------------------
Each clinical action is scored in [0,1] by a small, fully visible rule table
(``RISK_RULES`` below). The rules are intentionally simple and conservative so a
reviewer can read exactly why an action lands in Fast/Normal/Safe:

  * high-alert / look-alike medications, controlled substances, and
    order-entry actions flagged STAT/critical  -> high risk (>= 0.70 -> SAFE)
  * routine therapeutic orders & standard meds  -> medium risk (0.30-0.70 -> NORMAL)
  * informational / documentation / low-impact  -> low risk (< 0.30 -> FAST)

You SHOULD adapt this table to your institutional high-alert list; the point is
that the mapping is explicit and regenerable, not that this exact table is
canonical. The routing thresholds (0.30 / 0.70) come from the committed engine.

Usage
-----
    python scripts/extract_mimic.py --mimic-path /path/to/mimic-iv-2.2
    MIMIC_IV_PATH=/path/to/mimic-iv-2.2 python scripts/extract_mimic.py
    python scripts/extract_mimic.py --limit 50000   # cap rows for a quick pass
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Tuple

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
RESULTS = ROOT / "results"
sys.path.insert(0, str(SRC))

from orasr import ORASRRouter, ReasoningPath  # noqa: E402

# --------------------------------------------------------------------------
# Clinical-action sources within a standard MIMIC-IV root (hosp module).
# Each entry: (relative path, free-text columns used to score the action).
# --------------------------------------------------------------------------
ACTION_SOURCES = [
    # prescriptions: drug name + route drive the medication-safety risk.
    ("hosp/prescriptions.csv.gz", ("drug", "route", "drug_type")),
    # provider order entry: order type / transaction drive procedural risk.
    ("hosp/poe.csv.gz", ("order_type", "transaction_type")),
]

# --------------------------------------------------------------------------
# Transparent risk rules. First matching rule wins; default = NORMAL band.
# A rule is (keyword-set, risk_score). Keywords are matched case-insensitively
# against the concatenated free-text columns of the action row.
# --------------------------------------------------------------------------
RISK_RULES: Tuple[Tuple[Tuple[str, ...], float], ...] = (
    # High risk -> SAFE pathway (>= 0.70). High-alert / controlled / critical.
    (("insulin", "heparin", "warfarin", "fentanyl", "morphine", "hydromorphone",
      "potassium chloride", "vasopressin", "norepinephrine", "epinephrine",
      "chemotherap", "neuromuscular", "propofol", "stat", "critical",
      "controlled"), 0.85),
    # Medium risk -> NORMAL pathway (0.30-0.70). Routine therapeutic orders.
    (("antibiotic", "tablet", "capsule", "injection", "iv", "medication",
      "main", "med", "lab", "imaging", "consult"), 0.50),
    # Low risk -> FAST pathway (< 0.30). Informational / documentation.
    (("note", "documentation", "info", "diet", "nursing", "vital",
      "observation"), 0.15),
)
DEFAULT_RISK = 0.50  # unmatched actions default to the NORMAL band


def score_action(fields: Iterable[str]) -> float:
    """Map an action's free-text fields to a risk score using RISK_RULES."""
    text = " ".join(str(f) for f in fields if f is not None).lower()
    for keywords, risk in RISK_RULES:
        if any(k in text for k in keywords):
            return risk
    return DEFAULT_RISK


def _iter_rows(path: Path, columns: Tuple[str, ...], limit: Optional[int]):
    """Stream selected columns from a (gzipped) MIMIC CSV without pandas."""
    import csv

    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        present = [c for c in columns if c in (reader.fieldnames or [])]
        if not present:
            return
        for i, row in enumerate(reader):
            if limit is not None and i >= limit:
                break
            yield tuple(row.get(c, "") for c in present)


def resolve_mimic_path(cli_path: Optional[str]) -> Optional[Path]:
    raw = cli_path or os.environ.get("MIMIC_IV_PATH")
    if not raw:
        return None
    p = Path(raw).expanduser()
    return p if p.exists() else None


def extract(mimic_root: Path, limit: Optional[int]) -> Dict[str, Any]:
    """Route every extracted clinical action and tally the pathway distribution."""
    router = ORASRRouter(enable_fast_path=True, enable_audit=False)

    def identity_action(data: Any) -> Any:
        return data

    counts = {"FAST": 0, "NORMAL": 0, "SAFE": 0}
    risk_hist = {"<0.30": 0, "0.30-0.70": 0, ">=0.70": 0}
    total = 0
    sources_used = []

    for rel, cols in ACTION_SOURCES:
        path = mimic_root / rel
        if not path.exists():
            continue
        sources_used.append(rel)
        for fields in _iter_rows(path, cols, limit):
            risk = score_action(fields)
            # Routing decision comes from the committed engine, not from us.
            pathway = router._select_pathway(risk, require_approval=False)
            counts[pathway.name] += 1
            if risk < 0.30:
                risk_hist["<0.30"] += 1
            elif risk < 0.70:
                risk_hist["0.30-0.70"] += 1
            else:
                risk_hist[">=0.70"] += 1
            total += 1

    if total == 0:
        raise RuntimeError(
            "No clinical-action rows were read. Checked sources: "
            + ", ".join(rel for rel, _ in ACTION_SOURCES)
            + f" under {mimic_root}. Verify this is a MIMIC-IV root with the "
            "hosp/ module, or edit ACTION_SOURCES for your extract layout."
        )

    pct = {k: round(100.0 * v / total, 2) for k, v in counts.items()}
    return {
        "mimic_root": str(mimic_root),
        "sources_used": sources_used,
        "row_limit_per_source": limit,
        "total_actions": total,
        "pathway_distribution": counts,
        "pathway_distribution_pct": pct,
        "risk_histogram": risk_hist,
        "routing_thresholds": {
            "fast_lt": router.FAST_PATH_THRESHOLD,
            "safe_ge": router.SAFE_PATH_THRESHOLD,
        },
        "note": (
            "Regenerated from the user's credentialed MIMIC-IV copy via the "
            "transparent RISK_RULES mapping. These numbers are NOT hardcoded and "
            "will differ from the manuscript if your cohort filter / high-alert "
            "list differs. The manuscript reports 8,412 actions at "
            "58.1/31.5/10.4% (Fast/Normal/Safe); reproduce on your data and "
            "report what you obtain."
        ),
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="Extract MIMIC-IV routing distribution (data-free).")
    ap.add_argument("--mimic-path", default=None,
                    help="MIMIC-IV root (else env MIMIC_IV_PATH).")
    ap.add_argument("--limit", type=int, default=None,
                    help="Optional per-source row cap for a quick pass.")
    ap.add_argument("--out", default=str(RESULTS / "mimic_distribution.json"),
                    help="Output JSON path.")
    args = ap.parse_args()

    mimic_root = resolve_mimic_path(args.mimic_path)
    if mimic_root is None:
        sys.stderr.write(
            "ERROR: MIMIC-IV not found.\n"
            "  This script requires CREDENTIALED PhysioNet access to MIMIC-IV.\n"
            "  Provide the dataset root via --mimic-path or the MIMIC_IV_PATH env var,\n"
            "  e.g.  python scripts/extract_mimic.py --mimic-path /data/mimic-iv-2.2\n"
            "  No data is bundled and no distribution is fabricated. Exiting.\n"
        )
        sys.exit(2)

    try:
        res = extract(mimic_root, args.limit)
    except RuntimeError as exc:
        sys.stderr.write(f"ERROR: {exc}\n")
        sys.exit(3)

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(json.dumps(res, indent=2), encoding="utf-8")

    print("MIMIC-IV routing distribution (regenerated from YOUR credentialed copy)")
    print("  total actions     :", res["total_actions"])
    print("  pathway counts    :", res["pathway_distribution"])
    print("  pathway pct        :", res["pathway_distribution_pct"])
    print("  sources used      :", res["sources_used"])
    print("  (manuscript reports 8,412 @ 58.1/31.5/10.4% -- yours may differ)")
    print("  written to", args.out)


if __name__ == "__main__":
    main()
